version: "3"

services:
  php:
    build: "./docker/php/"
    volumes:
      - "./:/home/www"
  db:
    image: "postgres"
    restart: always
    ports:
      - 2345:5432
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: supersecretpass
  server:
    image: "nginx"
    ports:
     - 80:80
    volumes:
      - "./:/home/www"
      - "./docker/server/nginx.conf:/etc/nginx/nginx.conf"
  composer:
    image: "composer"
    volumes:
      - "./:/home/www"
